server:
  port: 8082
  servlet:
    context-path: /hello

girl:
  name: B
  age: 18
  content: content:${girl.name},age:${girl.age}

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.96.200.122:3306/girl?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true